
double AlignStrings(
    char * const,
    char * const,
    char **,
    char **,
    const long,
    const long * const,
    const double * const,
    const long,
    const char,
    const double,
    const double,
    const double,
    const double,
    const double,
    const long,
    const long,
    const long,
    const double * const,
    const double * const,
    const double * const,
    const double * const,
    double * const,
    double * const,
    double * const
    );
