#!/usr/bin/env python3

import signal

from Bio import AlignIO
from Bio.Align import MultipleSeqAlignment
from BioExt.io import BamIO
from BioExt.misc import gapful

import pysam


def main(bam_file, out_handle):

    try:
        signal.signal(signal.SIGPIPE, signal.SIG_DFL)
    except ValueError:
        pass

    seqs = [gapful(record, insertions=False) for record in BamIO.parse(bam_file)]

    samfile = pysam.Samfile(bam_file, 'rb')
    length = samfile.header['SQ'][0]['LN']
    samfile.close()

    msa = MultipleSeqAlignment(
        [seq + ('-' * (length - len(seq))) for seq in seqs]
        )

    AlignIO.write(msa, out_handle, 'fasta')

    return 0


if __name__ == '__main__':
    import sys
    import argparse

    parser = argparse.ArgumentParser(
        description='convert a BAM file to a MSA, removing insertions'
        )

    parser.add_argument(
        'input',
        metavar='INPUT',
        type=argparse.FileType('rb'),
        help='input BAM file'
        )
    parser.add_argument(
        'output',
        default=sys.stdout,
        metavar='OUTPUT',
        type=argparse.FileType('w'),
        help='output FASTA MSA file'
        )

    args = None
    retcode = -1
    try:
        args = parser.parse_args()
        bam_file = args.input.name
        args.input.close()
        retcode = main(bam_file, args.output)
    finally:
        if args is not None:
            if args.output != sys.stdout:
                args.output.close()

    sys.exit(retcode)
