#!/usr/bin/env python3

from __future__ import division, print_function

import sys

import BioExt.scorematrices

from Bio import SeqIO

from BioExt.io import BamIO
from BioExt.misc import compute_cigar, gapless
from BioExt.scorematrices import (
    DNAScoreMatrix,
    FrequenciesError,
    LazyScoreMatrix,
    ProteinScoreMatrix
    )
from BioExt.uds import _align_par


SCORE_MATRICES = {}


for key in dir(BioExt.scorematrices):
    val = getattr(BioExt.scorematrices, key)
    if isinstance(val, (DNAScoreMatrix, LazyScoreMatrix, ProteinScoreMatrix)):
        SCORE_MATRICES[key] = val


def main(
        input_handle,
        output_handle,
        reference,
        expected_identity,
        alphabet,
        reverse_complement,
        score_matrix,
        discard_handle,
        do_sort,
        quiet):

    try:
        score_matrix_ = score_matrix.load()
    except:
        raise RuntimeError('could not load the score matrix')

    if ((alphabet == 'dna' and not isinstance(score_matrix, DNAScoreMatrix)) and
            not isinstance(score_matrix, ProteinScoreMatrix)):
        raise ValueError(
            'DNA alphabet requires a DNA score matrix, '
            'while amino and codon alphabets require a protein score matrix'
            )

    do_codon = alphabet == 'codon'

    records = SeqIO.parse(input_handle, 'fasta')

    # grab the first, make it gapless once and for all
    if reference is None:
        reference = gapless(next(records))

        def allseqs(records):
            yield compute_cigar(reference, reference)
            for record in records:
                yield record
    else:
        def allseqs(records):
            for record in records:
                yield record

    if discard_handle:
        def discard(record):
            SeqIO.write([gapless(record.upper())], discard_handle, 'fasta')
    else:
        discard = None

    def output(records):
        BamIO.write(
            allseqs(records),
            output_file,
            reference
            )

    retcode = -1
    try:
        _align_par(
            reference,
            records,
            score_matrix_,
            do_codon,
            reverse_complement,
            expected_identity,
            discard,
            output,
            quiet
            )
        if do_sort:
            BamIO.sort(output_file)
        retcode = 0
    except FrequenciesError:
        print(
            'supplied score-matrix does not imply a frequency distribution:',
            'please choose another matrix if you must filter on expected identity',
            file=sys.stderr
            )

    return retcode


if __name__ == '__main__':
    import argparse

    from os import remove
    from os.path import getsize

    from BioExt import __version__ as version
    from BioExt.references import hxb2, nl4_3

    references = {
        'HXB2_env': hxb2.env,
        'HXB2_gag': hxb2.gag,
        'HXB2_int': hxb2.int,
        'HXB2_nef': hxb2.nef,
        'HXB2_pol': hxb2.pol,
        'HXB2_pr': hxb2.pr,
        'HXB2_prrt': hxb2.prrt,
        'HXB2_rev': hxb2.rev,
        'HXB2_rt': hxb2.rt,
        'HXB2_tat': hxb2.tat,
        'HXB2_vif': hxb2.vif,
        'HXB2_vpr': hxb2.vpr,
        'HXB2_vpu': hxb2.vpu,
        'NL4-3_prrt': nl4_3.prrt
        }

    def reference(string):
        if string in references:
            return references[string].load()
        try:
            with open(string) as handle:
                ref = next(SeqIO.parse(handle, 'fasta'))
            return ref
        except:
            msg = "'{0}' does not exist or is not a valid FASTA file".format(string)
            raise argparse.ArgumentTypeError(msg)

    def probability(string):
        try:
            p = float(string)
            if p < 0 or p > 1:
                raise ValueError()
            return p
        except ValueError:
            msg = "'{0}' is not a probability in [0, 1]".format(string)
            raise argparse.ArgumentTypeError(msg)

    parser = argparse.ArgumentParser(
        description=(
            'align sequences to a reference using '
            'a codon alignment algorithm and output to a BAM file'
            )
        )

    parser.add_argument(
        'input',
        metavar='INPUT',
        type=argparse.FileType('r'),
        help='INPUT FASTA file'
        )
    parser.add_argument(
        'output',
        metavar='OUTPUT',
        type=argparse.FileType('wb'),
        help='send BAM to OUTPUT'
        )
    parser.add_argument(
        '-r', '--reference',
        metavar='REFERENCE',
        type=reference,
        help='REFERENCE FASTA file or {{{0}}}'.format(', '.join(references.keys()))
        )
    parser.add_argument(
        '-e', '--expected-identity',
        type=probability,
        default=None,
        help='discard sequences that are insufficiently identical to the reference'
        )
    parser.add_argument(
        '-a', '--alphabet',
        metavar='ALPHABET',
        choices=('amino', 'dna', 'codon'),
        default='codon',
        help='perform an alignment using one of {{{0}}} [default=codon]'.format(
            ', '.join(('amino', 'dna', 'codon'))
            )
        )
    parser.add_argument(
        '-m', '--score-matrix',
        metavar='SCOREMATRIX',
        choices=sorted(SCORE_MATRICES.keys()),
        default='BLOSUM62',
        help='parameterize using one of {{{0}}} [default=BLOSUM62]'.format(
            ', '.join(SCORE_MATRICES.keys())
            )
        )
    parser.add_argument(
        '-D', '--discard',
        metavar='DISCARD',
        type=argparse.FileType('w'),
        help='discarded sequences are sent to DISCARD'
        )
    parser.add_argument(
        '-R', '--reverse-complement',
        action='store_true',
        help=(
            "also align the reverse complement of each query sequence, "
            "returning it if the alignment is superior"
            )
        )
    parser.add_argument(
        '-S', '--no-sort',
        dest='sort',
        action='store_false',
        help='do NOT sort the resulting BAM file [the default is to sort]'
        )
    parser.add_argument(
        '-q', '--quiet',
        action='store_true',
        help='do not print status update messages'
        )
    parser.add_argument(
        '-v', '--version',
        action='version',
        version='BioExt version {0}'.format(version),
        help='print version information and exit'
        )

    args = None
    retcode = -1
    try:
        args = parser.parse_args()
        output_file = args.output.name
        args.output.close()
        retcode = main(
            args.input,
            output_file,
            args.reference,
            args.expected_identity,
            args.alphabet,
            args.reverse_complement,
            SCORE_MATRICES[args.score_matrix],
            args.discard,
            args.sort,
            args.quiet
        )
    finally:
        if args is not None:
            # close input file handle
            if args.input and args.input != sys.stdin:
                args.input.close()
            if args.discard and args.discard != sys.stdout:
                args.discard.close()
                try:
                    if getsize(args.discard.name) == 0:
                        remove(args.discard.name)
                except:
                    pass

    sys.exit(retcode)
